source "https://rubygems.org"

# Specify your gem's dependencies in core_matrix_cli.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

gem "minitest", "~> 6.0"
gem "webrick"

gem "rubocop", "~> 1.21", require: false
gem "rubocop-rails-omakase", require: false
