require_relative "lib/core_matrix_cli"

task default: :test

desc "Run the full CLI test suite"
task :test do
  ruby "-Itest", "-e", <<~RUBY
    Dir.glob("test/**/*_test.rb").sort.each do |path|
      require File.expand_path(path)
    end
  RUBY
end
