inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  TargetRubyVersion: 4.0
  Exclude:
    - references/**/*
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: diff_comma

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  EnforcedStyle: around

Layout/TrailingEmptyLines:
  Enabled: true
  EnforcedStyle: final_newline

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never
