# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in cybros_nexus.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

gem "minitest", "~> 6.0"

gem "rubocop", "~> 1.21", require: false
gem "rubocop-rails-omakase", require: false
