<%
  runtime_topology = ActiveSupport::ConfigurationFile.parse(Rails.root.join("config/runtime_topology.yml")) || {}
  runtime_topology = runtime_topology.deep_stringify_keys
%>
default: &default
  dispatchers:
<% runtime_topology.fetch("dispatchers").each do |dispatcher| %>
    - polling_interval: <%= dispatcher.fetch("polling_interval") %>
      batch_size: <%= dispatcher.fetch("batch_size") %>
<% end %>
  workers:
<% runtime_topology.fetch("queues").each_value do |worker| %>
    - queues: "<%= worker.fetch("name") %>"
      threads: <%= ENV.fetch(worker.fetch("threads_env"), worker.fetch("default_threads")) %>
      processes: <%= ENV.fetch(worker.fetch("processes_env"), worker.fetch("default_processes")) %>
      polling_interval: <%= worker.fetch("polling_interval") %>
<% end %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
