default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "runtime_prepare_round"
      threads: <%= ENV.fetch("SQ_THREADS_PREPARE", 2) %>
      processes: <%= ENV.fetch("SQ_PROCESSES_PREPARE", 1) %>
      polling_interval: 0.1
    - queues: "runtime_pure_tools"
      threads: <%= ENV.fetch("SQ_THREADS_PURE_TOOLS", 6) %>
      processes: <%= ENV.fetch("SQ_PROCESSES_PURE_TOOLS", 1) %>
      polling_interval: 0.1
    - queues: "runtime_process_tools"
      threads: <%= ENV.fetch("SQ_THREADS_PROCESS_TOOLS", 2) %>
      processes: <%= ENV.fetch("SQ_PROCESSES_PROCESS_TOOLS", 1) %>
      polling_interval: 0.1
    - queues: "runtime_control"
      threads: <%= ENV.fetch("SQ_THREADS_RUNTIME_CONTROL", 2) %>
      processes: <%= ENV.fetch("SQ_PROCESSES_RUNTIME_CONTROL", 1) %>
      polling_interval: 0.1
    - queues: "maintenance"
      threads: <%= ENV.fetch("SQ_THREADS_MAINTENANCE", 1) %>
      processes: <%= ENV.fetch("SQ_PROCESSES_MAINTENANCE", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
