version: 1

dispatchers:
  - polling_interval: 1
    batch_size: 500

queues:
  prepare_round:
    name: runtime_prepare_round
    threads_env: SQ_THREADS_PREPARE
    default_threads: 2
    processes_env: SQ_PROCESSES_PREPARE
    default_processes: 1
    polling_interval: 0.1
  pure_tools:
    name: runtime_pure_tools
    threads_env: SQ_THREADS_PURE_TOOLS
    default_threads: 6
    processes_env: SQ_PROCESSES_PURE_TOOLS
    default_processes: 1
    polling_interval: 0.1
  process_tools:
    name: runtime_process_tools
    threads_env: SQ_THREADS_PROCESS_TOOLS
    default_threads: 2
    processes_env: SQ_PROCESSES_PROCESS_TOOLS
    default_processes: 1
    polling_interval: 0.1
  runtime_control:
    name: runtime_control
    threads_env: SQ_THREADS_RUNTIME_CONTROL
    default_threads: 2
    processes_env: SQ_PROCESSES_RUNTIME_CONTROL
    default_processes: 1
    polling_interval: 0.1
  maintenance:
    name: maintenance
    threads_env: SQ_THREADS_MAINTENANCE
    default_threads: 1
    processes_env: SQ_PROCESSES_MAINTENANCE
    default_processes: 1
    polling_interval: 0.1

database_pools:
  primary:
    env: FENIX_PRIMARY_DB_POOL
    default: 5
  queue:
    env: FENIX_QUEUE_DB_POOL
    default: 8
